
train_setting:
    is_seed_fixed: True
    seed: 12

optimizer_setting:
    model_lr: 0.005
    awl_lr: 0.01
    awl_weight_decay: 0.0


scheduler_setting:
    gamma: 0.05

model_setting:
    name: AMAN_model
    num_channels: 52

weight_module_setting:
    name: AWL_loss
    params: {'num':2}

trainer_setting:
    batch_size : 32
    num_epochs : 200
    order : 1
    model_save_path: "./weights/"

dataset_setting:
    train_dataset_dir: "./data/dataset_1/train_data_split_amp.mat"
    test_dataset_dir: "./data/dataset_1/test_data_split_amp.mat"